
// This file has been generated by the GUI designer. Do not modify.
namespace OpenGraal.MapGenerator
{
	public partial class TestWindow
	{
		private global::Gtk.IconView iconview1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget OpenGraal.MapGenerator.TestWindow
			this.Name = "OpenGraal.MapGenerator.TestWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("TestWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child OpenGraal.MapGenerator.TestWindow.Gtk.Container+ContainerChild
			this.iconview1 = new global::Gtk.IconView ();
			this.iconview1.CanFocus = true;
			this.iconview1.Name = "iconview1";
			this.Add (this.iconview1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
