
// This file has been generated by the GUI designer. Do not modify.
namespace OpenGraal.GraalIM
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action FileAction;
		private global::Gtk.Action closeAction;
		private global::Gtk.Action HelpAction;
		private global::Gtk.Action aboutAction;
		private global::Gtk.Table table1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label label1;
		private global::Gtk.Label label2;
		private global::Gtk.Label label3;
		private global::Gtk.HPaned hpaned1;
		public global::Gtk.Notebook notebook2;
		private global::Gtk.Table table3;
		private global::Gtk.Entry entry2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.TextView StatusLog;
		private global::Gtk.Button SendButton;
		private global::Gtk.Label StatusTabLabel;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.NodeView PlayerList;
		private global::Gtk.MenuBar menubar1;

		protected virtual void Build ()
		{
			//global::Stetic.Gui.Initialize (this);
			// Widget OpenGraal.GraalIM.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("_File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_File");
			w1.Add (this.FileAction, null);
			this.closeAction = new global::Gtk.Action ("closeAction", global::Mono.Unix.Catalog.GetString ("_Exit"), null, "gtk-close");
			this.closeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Exit");
			w1.Add (this.closeAction, null);
			this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("_Help"), null, null);
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Help");
			w1.Add (this.HelpAction, null);
			this.aboutAction = new global::Gtk.Action ("aboutAction", global::Mono.Unix.Catalog.GetString ("_About"), null, "gtk-about");
			this.aboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_About");
			w1.Add (this.aboutAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.WidthRequest = 1008;
			this.HeightRequest = 418;
			this.CanFocus = true;
			this.Name = "OpenGraal.GraalIM.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("GraalIM");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("OpenGraal.GraalIM.Resources.rcicon.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.DefaultWidth = 640;
			this.DefaultHeight = 480;
			this.DestroyWithParent = true;
			// Container child OpenGraal.GraalIM.MainWindow.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.ColumnSpacing = ((uint)(1));
			// Container child table1.Gtk.Table+TableChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.HeightRequest = 21;
			this.hbox1.Name = "hbox1";
			this.hbox1.Homogeneous = true;
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.hbox1.Add (this.label2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label2]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.hbox1.Add (this.label3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label3]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.table1.Add (this.hbox1);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox1]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(0));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 812;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.notebook2 = new global::Gtk.Notebook ();
			this.notebook2.CanFocus = true;
			this.notebook2.Name = "notebook2";
			this.notebook2.CurrentPage = 0;
			this.notebook2.EnablePopup = true;
			this.notebook2.Scrollable = true;
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.table3 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table3.Name = "table3";
			// Container child table3.Gtk.Table+TableChild
			this.entry2 = new global::Gtk.Entry ();
			this.entry2.HeightRequest = 30;
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.ActivatesDefault = true;
			this.entry2.InvisibleChar = '•';
			this.table3.Add (this.entry2);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table3 [this.entry2]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.StatusLog = new global::Gtk.TextView ();
			this.StatusLog.CanFocus = true;
			this.StatusLog.Name = "StatusLog";
			this.StatusLog.Editable = false;
			this.StatusLog.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow2.Add (this.StatusLog);
			this.table3.Add (this.GtkScrolledWindow2);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3 [this.GtkScrolledWindow2]));
			w8.RightAttach = ((uint)(2));
			// Container child table3.Gtk.Table+TableChild
			this.SendButton = new global::Gtk.Button ();
			this.SendButton.WidthRequest = 89;
			this.SendButton.HeightRequest = 21;
			this.SendButton.CanFocus = true;
			this.SendButton.Name = "SendButton";
			this.SendButton.UseUnderline = true;
			this.SendButton.Label = global::Mono.Unix.Catalog.GetString ("Send");
			this.table3.Add (this.SendButton);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table3 [this.SendButton]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook2.Add (this.table3);
			// Notebook tab
			this.StatusTabLabel = new global::Gtk.Label ();
			this.StatusTabLabel.CanDefault = true;
			this.StatusTabLabel.Name = "StatusTabLabel";
			this.StatusTabLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Status");
			this.notebook2.SetTabLabel (this.table3, this.StatusTabLabel);
			this.StatusTabLabel.ShowAll ();
			this.hpaned1.Add (this.notebook2);
			global::Gtk.Paned.PanedChild w11 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.notebook2]));
			w11.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.WidthRequest = 200;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.PlayerList = new global::Gtk.NodeView ();
			this.PlayerList.CanFocus = true;
			this.PlayerList.Name = "PlayerList";
			this.PlayerList.SearchColumn = 0;
			this.GtkScrolledWindow.Add (this.PlayerList);
			this.hpaned1.Add (this.GtkScrolledWindow);
			this.table1.Add (this.hpaned1);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.hpaned1]));
			w14.TopAttach = ((uint)(2));
			w14.BottomAttach = ((uint)(3));
			w14.RightAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.UIManager.AddUiFromString ("<ui><menubar name=\'menubar1\'><menu name=\'FileAction\' action=\'FileAction\'><menuite" +
			"m name=\'closeAction\' action=\'closeAction\'/></menu><menu name=\'HelpAction\' action" +
			"=\'HelpAction\'><menuitem name=\'aboutAction\' action=\'aboutAction\'/></menu></menuba" +
			"r></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.HeightRequest = 21;
			this.menubar1.Name = "menubar1";
			this.table1.Add (this.menubar1);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.menubar1]));
			w15.RightAttach = ((uint)(2));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.StatusTabLabel.HasDefault = true;
			this.Show ();
			this.DestroyEvent += new global::Gtk.DestroyEventHandler (this.formclosed);
			this.Hidden += new global::System.EventHandler (this.formclosed);
			this.closeAction.Activated += new global::System.EventHandler (this.Exit);
			this.SendButton.Clicked += new global::System.EventHandler (this.SendButtonPressed);
			this.entry2.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.IRC_ChatBar);
		}
	}
}
